Description: Udacity aws devops nanodegree project2 - This template deploys a VPC, Subnet, Internet gateway and route table

Parameters:
  EnvironmentName:
    Description: An Environment name that will be prefixed to resources
    Type: String
  
  VpcCIDR:
    Description: The IP range (CIDR notation) for vpc
    Type: String
    Default: 10.0.0.0/16

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsHostnames: true
      Tags:
      - Key: Name
        Value: !Ref EnvironmentName

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: !Ref EnvironmentName
  
  VPCInternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
